---
title: "VSlope"
format: html
editor: visual
---

# VSlope

The vo2max_qc document became bloated, so I moved the calculation of V-slope to this document. I hope I can make it a bit simpler with the segmented package.

```{r}
library(renv)
library(readxl)
library(dplyr)
library(here)
library(snakecase)
library(lubridate)
library(ggplot2)
library(car)
library(writexl)
library(LMMstar)
library(plotly)
library(stringr)
#renv::install("BSDA")
#library(BSDA)
#renv::init()
#renv::install("zoo")
library(zoo)
#install.packages("targets")
#library(targets)
#use_targets()
#renv::install("ggpmisc")
#update("ggplot2")
library(ggpubr)
#install("segmented")
library(segmented)
set.seed(42069)
here()

mITT =T
PP=F
```

## Get sample data

```{r}
data<-
  read_excel(path = here("Data","VO2FromR","VO2maxWrittenByR_lup_050_baseline.xlsx"))

mod_lm<-lm(VCO2 ~ VO2, data = data)
summary(mod_lm)

seggy<-segmented(
  mod_lm
)

summary(seggy)
plot(seggy)+points(data$VO2, data$VCO2, col='blue')

confint(seggy)

predict(seggy, newdata = data.frame(VO2=confint(seggy)[1]), interval = "confidence")

tiff(
  file =  here("Output","graphics","test","test_segment.tiff"),
  width = 800, height = 800)
plot(seggy)+points(data$VO2, data$VCO2, col='blue')
dev.off()

vslope_keep <- c(0.3,0.8)


 df_not_considered<-
      data%>%
      dplyr::filter(
        VO2 < quantile(data$VO2, vslope_keep[1]) |
        VO2 > quantile(data$VO2, vslope_keep[2])
      )

 df_vslope<-
      data%>%
      dplyr::filter(
        VO2 >= quantile(data$VO2, vslope_keep[1]) &
        VO2 <= quantile(data$VO2, vslope_keep[2])
      )
 
 mod_lm<-lm(VCO2 ~ VO2, data = df_vslope)
summary(mod_lm)

seggy<-segmented(
  mod_lm
)

summary(seggy)
confint(seggy)

par(oma=c(0,0,0,0)) # all sides have 3 lines of space
par(mar=c(5,5,2,2))
plot(seggy, res=F,
     ylab=bquote(~ring(V)~CO[2]~(ml/min)),
     xlab=bquote(~ring(V)~O[2]~(ml/min)),
     ylim =c(0,1.1*max(data$VCO2)), 
     xlim = c(0,1.1*max(data$VO2)))+
  points(df_vslope$VO2[df_vslope$VO2 <
                         confint(seggy)[1]], 
         df_vslope$VCO2[df_vslope$VO2 <
                          confint(seggy)[1]], 
         col='blue')+
  points(df_vslope$VO2[df_vslope$VO2 >
                         confint(seggy)[1]], 
         df_vslope$VCO2[df_vslope$VO2 >
                          confint(seggy)[1]], col='red')+
  points(df_not_considered$VO2,df_not_considered$VCO2, col="gray")



```
